### ISSUE TITLE
ImportError: cannot import name ‘properties’ from ‘keyring.util’

### ISSUE THREAD

**Issue by Konubinix** [ewjoachim/bitwarden-keyring#7]
I'm not using bitwarden, but on the computer of a friend, there is

```
  File “/usr/local/lib/python3.11/site-packages/bitwarden_keyring/__init__.py”, line 8, in <module> from keyring.util import properties
ImportError: cannot import name ‘properties’ from ‘keyring.util’
```

This module was indeed removed

https://github.com/jaraco/keyring/commit/b8ee1bd98c03fbe4dfd4af9671755954fb868d7f

I don't know what it does, so I cannot recommand anything to fix this, but according to the deprecation warning that this commit removed

```
warnings.warn(
    "Properties from keyring.util are no longer supported. "
    "Use jaraco.classes.properties instead.",
    DeprecationWarning,
)
```
I don't know what jaraco is, but I assume you can simply replace the problematic import with `from jaraco.classes import properties`

**Comment by ewjoachim** [comment]
https://pypi.org/project/bitwarden-keyring/0.3.1/

Thank you very much, have a nice day.
